"""Initial migration.

Revision ID: 3b5a6e511c1d
Revises: 
Create Date: 2023-06-18 00:53:46.909386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b5a6e511c1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username2')
        batch_op.drop_column('username2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username2', mysql.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_user_username2', ['username2'], unique=False)

    # ### end Alembic commands ###
