"""empty message

Revision ID: 8d0a3c28f426
Revises: 3b5a6e511c1d
Create Date: 2023-06-18 00:55:49.696383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0a3c28f426'
down_revision = '3b5a6e511c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username2', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_username2'), ['username2'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username2'))
        batch_op.drop_column('username2')

    # ### end Alembic commands ###
